project:
  type: website

website:
  title: "Allison Lynn"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true

editor: visual

