project:
  type: website

website:
  title: "Allison Lynn"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: projects.qmd
        text: Projects
      - href: awards.qmd
        text: Awards

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

